package br.com.model.view;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author guest01
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        PainelPrincipal = new javax.swing.JPanel();
        PainelSuperior = new javax.swing.JPanel();
        PainelInferior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btFuncionario = new javax.swing.JButton();
        btPaciente = new javax.swing.JButton();
        btAgenda = new javax.swing.JButton();
        btConvenio = new javax.swing.JButton();
        mBarOpcHelp = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miAgenda = new javax.swing.JMenuItem();
        miConvenio = new javax.swing.JMenuItem();
        miFuncionario = new javax.swing.JMenuItem();
        miPaciente = new javax.swing.JMenuItem();
        mAjuda = new javax.swing.JMenu();
        miSobre = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Janela Principal[EMJ]");
        setBackground(new java.awt.Color(255, 255, 255));

        PainelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        PainelSuperior.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout PainelSuperiorLayout = new javax.swing.GroupLayout(PainelSuperior);
        PainelSuperior.setLayout(PainelSuperiorLayout);
        PainelSuperiorLayout.setHorizontalGroup(
            PainelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PainelSuperiorLayout.setVerticalGroup(
            PainelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PainelInferior.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/model/images/Java.png"))); // NOI18N

        javax.swing.GroupLayout PainelInferiorLayout = new javax.swing.GroupLayout(PainelInferior);
        PainelInferior.setLayout(PainelInferiorLayout);
        PainelInferiorLayout.setHorizontalGroup(
            PainelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelInferiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        PainelInferiorLayout.setVerticalGroup(
            PainelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelInferiorLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel6.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        btFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/model/images/Secretaria.png"))); // NOI18N
        btFuncionario.setText("Funcionários");
        btFuncionario.setToolTipText("Informações sobre os funcionários (Nome, Endereço, Profissão, telefone, entre outros) Com as opções editar, excluir e cadastrar um novo.");
        btFuncionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btFuncionario.setContentAreaFilled(false);
        btFuncionario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFuncionario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFuncionarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(59, 225, 86, 0);
        jPanel6.add(btFuncionario, gridBagConstraints);

        btPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/model/images/Paciente.png"))); // NOI18N
        btPaciente.setText("Pacientes");
        btPaciente.setToolTipText("Informações sobre os pacientes (Nome, Endereço, telefone, convênio, entre outras) Com as opções editar, excluir e cadastrar um novo.");
        btPaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btPaciente.setContentAreaFilled(false);
        btPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPacienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(59, 18, 86, 0);
        jPanel6.add(btPaciente, gridBagConstraints);

        btAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/model/images/Calendario.png"))); // NOI18N
        btAgenda.setText("Agenda Médica");
        btAgenda.setToolTipText("Aqui você poderá marcar as consultas médicas com os seus pacientes, desmarcar, editar.");
        btAgenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btAgenda.setContentAreaFilled(false);
        btAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btAgenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAgenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgendaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(59, 18, 86, 0);
        jPanel6.add(btAgenda, gridBagConstraints);

        btConvenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/model/images/Convenio.png"))); // NOI18N
        btConvenio.setText("Convênios");
        btConvenio.setToolTipText("Todos os seus parceiros com a consultório pode ser cadastrado, editado ou excluído por aqui.");
        btConvenio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btConvenio.setContentAreaFilled(false);
        btConvenio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btConvenio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btConvenio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConvenioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(59, 18, 86, 204);
        jPanel6.add(btConvenio, gridBagConstraints);

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout PainelPrincipalLayout = new javax.swing.GroupLayout(PainelPrincipal);
        PainelPrincipal.setLayout(PainelPrincipalLayout);
        PainelPrincipalLayout.setHorizontalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PainelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelPrincipalLayout.setVerticalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addComponent(PainelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(PainelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(PainelPrincipal, java.awt.BorderLayout.CENTER);

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Opções");

        miAgenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        miAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/model/images/Calendar.png"))); // NOI18N
        miAgenda.setText("Agenda Médica");
        miAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgendaActionPerformed(evt);
            }
        });
        jMenu1.add(miAgenda);

        miConvenio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        miConvenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/model/images/Partnership.png"))); // NOI18N
        miConvenio.setText("Convênios");
        miConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConvenioActionPerformed(evt);
            }
        });
        jMenu1.add(miConvenio);

        miFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        miFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/model/images/people.png"))); // NOI18N
        miFuncionario.setText("Funcionários");
        miFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(miFuncionario);

        miPaciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        miPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/model/images/customer.png"))); // NOI18N
        miPaciente.setText("Pacientes");
        miPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPacienteActionPerformed(evt);
            }
        });
        jMenu1.add(miPaciente);

        mBarOpcHelp.add(jMenu1);

        mAjuda.setText("Ajuda");

        miSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        miSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/model/images/Help.png"))); // NOI18N
        miSobre.setText("Sobre");
        miSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSobreActionPerformed(evt);
            }
        });
        mAjuda.add(miSobre);

        mBarOpcHelp.add(mAjuda);

        setJMenuBar(mBarOpcHelp);
        mBarOpcHelp.getAccessibleContext().setAccessibleName("");
        mBarOpcHelp.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFuncionarioActionPerformed
        FuncionarioListaGUI fg = new FuncionarioListaGUI();
        fg.setLocationRelativeTo(this);
        fg.setVisible(true);
    }//GEN-LAST:event_btFuncionarioActionPerformed

    private void btPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPacienteActionPerformed
        // TODO add your handling code here:
        PacienteListaGUI pg = new PacienteListaGUI();
        pg.setLocationRelativeTo(this);
        pg.setVisible(true);
    }//GEN-LAST:event_btPacienteActionPerformed

    private void btAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgendaActionPerformed
        ConsultaListaGUI cg = new ConsultaListaGUI();
        cg.setLocationRelativeTo(this);
        cg.setVisible(true);
    }//GEN-LAST:event_btAgendaActionPerformed

    private void btConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConvenioActionPerformed
        ConvenioListaGUI cg = new ConvenioListaGUI();
        cg.setLocationRelativeTo(this);
        cg.setVisible(true);
    }//GEN-LAST:event_btConvenioActionPerformed

    private void miFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFuncionarioActionPerformed
        FuncionarioListaGUI fg = new FuncionarioListaGUI();
        fg.setLocationRelativeTo(this);
        fg.setVisible(true);
    }//GEN-LAST:event_miFuncionarioActionPerformed

    private void miSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSobreActionPerformed
        java.awt.Desktop desktop = java.awt.Desktop.getDesktop();    
        try {
            desktop.open(new File("G:\\Curso\\PIC I\\AgendaMedica\\src\\br\\com\\model\\help\\GABARITOREC.P2.pdf"));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao exibir documento de ajuda: " + ex.getMessage());
        }
    }//GEN-LAST:event_miSobreActionPerformed

    private void miAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgendaActionPerformed
        ConsultaListaGUI cg = new ConsultaListaGUI();
        cg.setLocationRelativeTo(this);
        cg.setVisible(true);
    }//GEN-LAST:event_miAgendaActionPerformed

    private void miConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConvenioActionPerformed
        ConvenioListaGUI cg = new ConvenioListaGUI();
        cg.setLocationRelativeTo(this);
        cg.setVisible(true);
    }//GEN-LAST:event_miConvenioActionPerformed

    private void miPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPacienteActionPerformed
        PacienteListaGUI pg = new PacienteListaGUI();
        pg.setLocationRelativeTo(this);
        pg.setVisible(true);
    }//GEN-LAST:event_miPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelInferior;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JPanel PainelSuperior;
    private javax.swing.JButton btAgenda;
    private javax.swing.JButton btConvenio;
    private javax.swing.JButton btFuncionario;
    private javax.swing.JButton btPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JMenu mAjuda;
    private javax.swing.JMenuBar mBarOpcHelp;
    private javax.swing.JMenuItem miAgenda;
    private javax.swing.JMenuItem miConvenio;
    private javax.swing.JMenuItem miFuncionario;
    private javax.swing.JMenuItem miPaciente;
    private javax.swing.JMenuItem miSobre;
    // End of variables declaration//GEN-END:variables
}
